### ISSUE TITLE
build a production release (the famous unwrap panic)

### ISSUE THREAD

**Issue by tooshel** [Satellite-im/WarpGUI#10]
when you run 
cargo run --release

You get a panic like this.

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/223338/189249022-b310c09d-4458-432a-a6bb-e2333a15808a.png">

Dev Notes: 
We are storing stuff in static variables using atomref stuff in that library, but under release it seems to cause that panic when running.

**Comment by calogero93** [comment]
It was a bit hard but I did it. I used the last version of dioxus pulled from github,

**Comment by calogero93** [comment]
It was a bit hard but I did it.
I used the last version of dioxus pulled from github, but I had several conflicts with other libraries used, for example dioxus-toast or dioxus-heroicons because internally these libraries used old version of dioxus, I cloned that libraries form github, updated the dependencies locally, solved the error in each library and imported them from local in our implementation of WarpGUI, then I solved all the conflicts, change some old function with new functions provided by latest version of dioxus and tried to build in release mode.
The building was successful but I'm not able anymore to digit the pin from keyboard.

**Comment by calogero93** [comment]
I pushed this on branch WarpGUI-latest-dioxus

**Comment by tooshel** [comment]
If you look at the WARP-154-test branch you can see how Darius is fixing it. Basically, he's changing the way we use the dioxus lib.  Compare this https://github.com/Satellite-im/WarpGUI/blob/f45b5ff06313762fae2c288d214a1b35921f3f8b/src/main.rs#L31 to what you see in the dev branch. He's not done yet but the changes he has made in that branch mean the app won't crash after the first screen like it's doing in dev.

**Comment by dariusc93** [comment]
@calogero93 is this still an issue in dev branch?

**Comment by tooshel** [comment]
@dariusc93 @calogero93 I was able to build it with the --release flag and then use my pin code and search for a friend and all that worked fine. If @calogero93 finds the same we can close this, eh?

**Comment by calogero93** [comment]
@tooshel I'm able to run in release mode too without problem, I think we can close it
