### ISSUE TITLE
feat: add button to close the msg-reply modal

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/WarpGUI#125]
proposed change drawn in red

![msg-reply-modal-edited](https://user-images.githubusercontent.com/8636602/196509219-4654c767-7958-4a78-a923-4da7379b75a1.png)

Currently if the user clicks on a message, a modal appears which allows the user to reply to that message. If they want to cancel the operation, they have to click outside the modal. I think it would be beneficial to add a button to close the modal. 

the button should probably go on the left. usually such a button would go on the top bar but this modal doesn't have that. I'm not sure what the exact ordering of buttons should be but to start with I drew it at the top of the left panel.

**Comment by asher5420** [comment]
*Need approval from Matt first. This is different than the current dev desktop version of Uplink, but is consistent with the mobile version.

Instead of having the chat reply open as a pop-up, have the menu with the Reply button option open as a pop-up (same as in the mobile app). To close the chat reply, the user can click outside of the Pop-up Menu area.

![Image](https://user-images.githubusercontent.com/115492815/199333755-35eac4ba-dcd9-4bda-89dc-49b320e074d1.png)

Mockups of user flow with notes can be viewed on Figma.

Figma Board-
Chats / Replying to a Chat:
https://www.figma.com/file/GrAhLmQWA2kfD1Nw9nd24m/Chats-%2F-Landing-Page?node-id=0%3A1

**Comment by asher5420** [comment]
![Image](https://user-images.githubusercontent.com/115492815/199336872-6c3b0e99-0643-46e5-8cc9-8e9d56027b86.png)

**Component Specs:**

• Full Component Height: 11 rem (176px) Full Component Width: 19.5 rem (312px)  

• Emoji-Picker Bar Height: 3 rem (48px) Width: 15.5 rem (248px)  

• Emoji Menu Button: 3 rem x 3 rem (48px x 48px)  

• Full Dialog Box / Pop-up: Height: 7 rem (112px) Width: 19.5 rem (312px)  

• Dialog Box / Pop-up Text Options: Height: 3 rem (48px) Width: 19.5 rem (312px)

•   Padding Between Widgets: 1 rem (16px)  

• Drop Shadow: 0px 1px 6px 2px (rgba: 13, 14, 22, 0.65) (border-radius: 4px)

**Comment by lgmarchi** [comment]
@InfamousVague and @sdwoodbury, we have an close button on top right corner now. Ok to close this issue? 
![image](https://user-images.githubusercontent.com/63157656/201188402-ec5f0436-a411-4a0c-9388-73a93434e3df.png)

**Comment by phillsatellite** [comment]
@lgmarchi I think its okay to close. Worst comes to worst we can always re-open 👍
