### ISSUE TITLE
Emoji Reactions

### ISSUE THREAD

**Issue by InfamousVague** [Satellite-im/WarpGUI#152]
You should be able to hover a message and a reaction bar should come up below it, it should show the 5 most used emoji's by default, with a + button to open the emoji picker extension to pick a different reaction.

**Comment by asher5420** [comment]
*Need approval from Matt first. This is different than the current dev desktop version of Uplink, but is consistent with the mobile version.

Instead of hovering, how about have the user right-click on the chat they'd like to react to, to open the pop-up menu with the top 6 emoji list and "+" button. 


![Image](https://user-images.githubusercontent.com/115492815/199340774-242b0d3b-3784-4ae0-92c9-6ab13381907a.png)


![Image](https://user-images.githubusercontent.com/115492815/199340797-7fa94daa-9e1e-4d4c-b627-517356f86180.png)

Figma Board:
https://www.figma.com/file/GrAhLmQWA2kfD1Nw9nd24m/Chats-%2F-Landing-Page?node-id=0%3A1

**Comment by asher5420** [comment]
![Image](https://user-images.githubusercontent.com/115492815/199336872-6c3b0e99-0643-46e5-8cc9-8e9d56027b86.png)

**Component Specs:**

• Full Component Height: 11 rem (176px) Full Component Width: 19.5 rem (312px)  

• Emoji-Picker Bar Height: 3 rem (48px) Width: 15.5 rem (248px)  

• Emoji Menu Button: 3 rem x 3 rem (48px x 48px)  

• Full Dialog Box / Pop-up: Height: 7 rem (112px) Width: 19.5 rem (312px)  

• Dialog Box / Pop-up Text Options: Height: 3 rem (48px) Width: 19.5 rem (312px)

•   Padding Between Widgets: 1 rem (16px)  

• Drop Shadow: 0px 1px 6px 2px (rgba: 13, 14, 22, 0.65) (border-radius: 4px)
