### ISSUE TITLE
When user has multiple friends and goes into friends list, friends names will jump around

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#234]
**Issue:** Darius had experienced this issue once before and was curious that it might be a Warp issue. Issue is when user has a list of friends and they open the friends modal the profiles will jump around on the list of friends. 

**how to replicate:**
1. Create a primary account 
2. Open multiple new accounts and add the primary 
3. On primary account open friends modal after accepting request and notice friends list jump around 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/200352807-d4c9ba8f-6df2-46bd-8ba6-c172c21e53aa.mov

**Comment by dariusc93** [comment]
Just as a little note to his, This happened during testing with changes I made on warp-mp-ipfs, however this isnt directly related to warp as its doing what its intended. This is more so related to #140 as it is shifting around due to it being rendered and fetching the identity. Unless the UI does its own sorting, I would suggest using `HashSet` in place of `Vec` which would keep this from happening while its being rerendered, but resolving the issue noted prior would go along way as well.
