### ISSUE TITLE
Issues with Multi-line support 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#251]
**Issue:** Seems something went wrong with the Multi-Line support on MacOS it is currently not working 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/200616546-59b42c75-af95-458a-8c0b-cc4da46abc4a.mov

**Comment by sdwoodbury** [comment]
multiline within message replies has also changed

**Comment by dariusc93** [comment]
@phillsatellite can you confirm if this is still a issue?

**Comment by phillsatellite** [comment]
Confirmed can still replicate

**Comment by sdwoodbury** [comment]
I think that the resizable textarea performed better when it was a `textarea` instead of a `div`, such as at commit `0cb2696fd63875db68f2316994b45c1a92f6e2e3`. One shortcoming of that specific commit was that the resize script needed to be pasted in anywhere the TextArea was used, but this is an easy fix. If the TextArea could generate a random id, wrap itself in an HTML element with that id, and modify the re-size script to only apply to that element, there would be no risk of the resize scripts modifying the wrong textarea.  thoughts?  @InfamousVague

**Comment by InfamousVague** [comment]
> I think that the resizable textarea performed better when it was a `textarea` instead of a `div`, such as at commit `0cb2696fd63875db68f2316994b45c1a92f6e2e3`. One shortcoming of that specific commit was that the resize script needed to be pasted in anywhere the TextArea was used, but this is an easy fix. If the TextArea could generate a random id, wrap itself in an HTML element with that id, and modify the re-size script to only apply to that element, there would be no risk of the resize scripts modifying the wrong textarea. thoughts? @InfamousVague

I think it worked about the same, however we need to rethink this obviously because it's buggy, however keep in mind we need to support inline markdown in the textarea. This is something I've been thinking over in the UIkit but I haven't been able to come up with a perfect solution just yet.
