### ISSUE TITLE
Add search option

### ISSUE THREAD

**Issue by dariusc93** [Satellite-im/WarpGUI#27]
Currently the interface supports only adding another user by using the did key, however one can search for another user by using `MultiPass::get_identity`. 

Note: The underlining implementation in this UI should also display the short id using `Identity::short_id`, whether beside the username, or under, but in some way that can let one identify who is who by the last bits of the DID. 

EDIT: Correction

**Comment by InfamousVague** [comment]
@dariusc93 in order to make this a good first issue, could we include some loose steps here and a bit more elaboration on how the developer can go about adding this functionality? This could help open source contributions as well as new internal devs that are unfamiliar with how we've got things working.

**Comment by dariusc93** [comment]
One would use `MultiPass::get_identity(Identifier::user_name("username".into()))` which would return a list of identities from that username that can be displayed. If a shortid is included in the username (eg `username#abcdefg`) then it should display only that single user since it derives from the did key (which is also good to do additional verification but that isnt needed since its done internally)
