### ISSUE TITLE
Friend List should be displayed in alphabetical order 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#280]
**Issue:** Like title says, when you go to friends page the list of friends should be displayed in Alphabetical Order 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/200979917-019ecd09-c0d3-4b5d-be51-c55de97687e4.mov

**Comment by sdwoodbury** [comment]
in the `Friends` element, someone will need to call `utils::get_username_from_did` to turn all the `DID`s into strings and then sort them. Maybe create a `struct` consisting of a `DID` and `String` and implement `Ord` and `PartialOrd` (so that the usernames are compared) so you can sort a vector of said struct using `Vec::sort()`. 

doing it this way will address #281
