### ISSUE TITLE
Crash when sending the Satellite.im logo in chat

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#291]
**Issue:** When you send the Satellite logo I attached in this, app will crash a few moments after sending. It will also crash on the other users side. When you try to log back into the app again, app will crash

**Screenshot:**
<img width="1000" alt="Screenshot 2022-11-10 at 3 56 35 PM" src="https://user-images.githubusercontent.com/93608357/201204919-ab1262bc-c877-4e91-bab4-3b1cfc5d7a54.png">

https://user-images.githubusercontent.com/93608357/201206274-748217e0-a50a-4637-b05d-40a0e47697bb.mov

What causes the crash:

https://satellite.im/images/logo.webp

**Comment by dariusc93** [comment]
Might be similar to what @tooshel had when pasting a link. Since i dont see the backtrace in console, I can only assume its because the link didnt have a title, which the function tried to resolved before embedding it since its getting unwrapped. Solution around it would be to go to `utils/get_meta.rs` and have `test` be `let title = doc.find(Name("title")).next().map(|n| n.text()).unwrap_or_default();` then remove the `text.text()` at the bottom. This would yield a empty title if none is supplied.

**Comment by pavlzk** [comment]
Probably make sense to change `unwrap` to `unwrap_or_default()` for `icon` and `desc` since there can be `None`
