### ISSUE TITLE
Fix continuous message render

### ISSUE THREAD

**Issue by pavlzk** [Satellite-im/WarpGUI#417]
This part of code in `src/components/main/compose/messages/mod.rs` causes continuous rerender of messages component which probably lead high cpu usage
``` 
   let should_reload = use_future(&cx, (), |_| async move {
        tokio::time::sleep(std::time::Duration::from_secs(60)).await;
        true
    });
    
    if should_reload.value().is_some() {
        cx.needs_update();
    };
  ```

**Comment by dariusc93** [comment]
Based on the code it looks like it was meant to update the timestamp in the messages. I think its recurring because it needs to be restarted otherwise the future might still return as `Some(true)`. I think what should happen is that instead of trying to track the timestamp to show when something was last sent (eg "now", "x seconds ago", etc) we should just show the actual time on the message. If this is a must to do it this way then we should look into trying to update the context within `use_future` so it would force a rerender.
