### ISSUE TITLE
Search feature for finding friends isnt always working  

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#611]
**Issue:** Sometimes the search feature isnt always working. In screen recording you can see I can bring up Windows User and Sheldons account but can't find Yijing. She also had issues when trying to search for an account with the name User 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/207407689-c79cac21-295e-440b-8420-9e8703c56ead.mov

https://user-images.githubusercontent.com/93608357/207407746-844af9a3-2da6-4122-bb6d-9659ab85fe23.mov

**Comment by dariusc93** [comment]
Not exactly a bug. 

Just to give some clarification, the search feature by username will look up for those who been discovered already rather than automatically do it as it would do when utilizing the did key (since under current configuration used, it would check dht and dial out to the peer utilizing the did/public key). If the routing and discovery been successful and connection been have been establish the identity would have been provided to you (assuming things are up to date on both ends and no other routing issues)

Internally the other reasons for why it may not have been provided could be due to
 
1. networking issues on one or other side (or even in the network utilized for peer and content discovery)
2. Firewall or router blocking packets (unlikely since by default random ports are used on starting of the client, which is why one can use multiple clients on the same machine with the address, but still possible in some situations)
3. hole punching isnt successful (we utilize libp2p bootstrap as a relay, which can be used for hole punching but at times may be overloaded, which will be corrected in the future to use a relay found through dht that can be best used),  
4. Its falling back to the relay due to unsuccessful hole punching which may have  (which again falls back to the former statement about soon being able to find a suitable relay through dht) though even in such cases of using a relay, the relay protocol upstream usually have lower data transport limits so not every single but of data may make it through). 

The sync node that been a wip isnt used yet internally in a productive manner, which may aid in discovering users through the same (which would also be tied into who been discovered already) and offline stuff, but even then wont be solely depended to prevent a central point of failure to keep things truly decentralized.

If you are unable to find another user with their username, especially if you discovered already (eg they were searchable before but disappeared) or added them as a friend via did key, and they did not change their username (which you would have seen on the friends list), then it might be a bug, otherwise I dont consider the search portion to be a bug exactly and would probably close this issue out (can have it reopend if it was a bug from some of the things i mentioned)
