### ISSUE TITLE
Changed Username will not update until app is closed and reopened

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#637]
**Issue:** When you change your Username it will update everywhere except for the spot at the top of the App. To fix this the user has to close down the app and re open 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/208329679-4795a24d-be10-4ef7-9aa4-fae1eb700566.mov

**Comment by dariusc93** [comment]
Me personally, I do feel the username should be omitted from the window title, but that doesnt updates because nothing is setting the title afterwards. What could be done is after updating the username and it was successful to do something like

```rust
let window = use_window(&cx);

window.set_title(&format!("{} - {}", new_username, WINDOW_SUFFIX_NAME));
```

where `new_username` is the variable with the new name.
